### ISSUE TITLE
Initial Character Controls

### ISSUE THREAD

**Issue by soulerlunar** [RydalisDarx/gmtk24_godotgame#7]
Initial movement and branch for basic stuff.

**Comment by EstherMika0** [comment]
Commited a basic character control to main branch

**Comment by soulerlunar** [comment]
Implemented a double jump and dictionaries for defining when powers are unlocked and whether they can currently be used on [physics](https://github.com/RydalisDarx/gmtk24_godotgame/tree/physics) branch.
